apiVersion: v1
kind: Service
metadata:
  name: akash-node
  namespace: akash-services
  labels:
    app: akash-node
spec:
  ports:
    - port: 26657
      name: rpc
    - port: 1317
      name: api
  selector:
    app: akash-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: akash-node
  namespace: akash-services
spec:
  serviceName: "akash-node"
  replicas: 1
  selector:
    matchLabels:
      app: akash-node
  template:
    metadata:
      labels:
        app: akash-node
    spec:
      initContainers:
        - name: snapshot-downloader
          image: ubuntu:22.04
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              # Install deps
              apt-get update && apt-get install -y wget lz4 aria2 curl

              DATA_DIR="/root/.akash/data"
              if [ -f "$DATA_DIR/priv_validator_state.json" ]; then
                echo "✅ Data exists. Skipping snapshot download."
                exit 0
              fi

              echo "🧹 Cleaning fresh directory..."
              rm -rf /root/.akash/*

              # MIRROR LIST (Priority Order)
              MIRRORS=(
                "https://snapshots.polkachu.com/snapshots/akash/akash_latest.tar.lz4"
                "https://snapshots.nodejumper.io/akash/akash_latest.tar.lz4"
                "https://snapshots.kjnodes.com/akash/snapshot_latest.tar.lz4"
              )

              for URL in "${MIRRORS[@]}"; do
                echo "⬇️ Trying mirror: $URL"
                if aria2c -x5 -s5 --connect-timeout=10 --max-tries=3 "$URL" -o snapshot.tar.lz4; then
                  echo "✅ Download successful!"
                  echo "📦 Extracting..."
                  lz4 -c -d snapshot.tar.lz4 | tar -x -C /root/.akash
                  rm snapshot.tar.lz4
                  exit 0
                else
                  echo "❌ Failed to download from $URL. Trying next..."
                fi
              done

              echo "🚨 ALL MIRRORS FAILED. Check internet connection."
              exit 1
          volumeMounts:
            - name: data
              mountPath: /root/.akash
      containers:
        - name: node
          image: ghcr.io/akash-network/node:v0.34.1  # Stable version for Mainnet 14
          command: ["akash"]
          args:
            - "start"
            - "--rpc.laddr=tcp://0.0.0.0:26657"
            - "--minimum-gas-prices=0.025uakt"
            - "--x-crisis-skip-assert-invariants" # Performance boost
          ports:
            - containerPort: 26657
          volumeMounts:
            - name: data
              mountPath: /root/.akash
          resources:
            requests:
              cpu: "1000m"
              memory: "4Gi"
            limits:
              cpu: "4000m" # Burstable during sync
              memory: "8Gi"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Gi
