apiVersion: v1
kind: ServiceAccount
metadata:
  name: cognitod-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cognitod-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cognitod-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cognitod-role
subjects:
- kind: ServiceAccount
  name: cognitod-sa
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cognitod
  namespace: default
spec:
  selector:
    matchLabels:
      app: cognitod
  template:
    metadata:
      labels:
        app: cognitod
    spec:
      hostPID: true
      serviceAccountName: cognitod-sa
      containers:
      - name: cognitod
        image: cognitod:latest
        imagePullPolicy: Never
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: RUST_LOG
          value: "debug"
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: proc
          mountPath: /proc
          readOnly: true
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
